# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/default.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PWM_0_0/design_1_PWM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_PWM_0_0 || ORIG_REF_NAME==design_1_PWM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ROM_0_0/design_1_ROM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ROM_0_0 || ORIG_REF_NAME==design_1_ROM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_controlador_0_0/design_1_controlador_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_controlador_0_0 || ORIG_REF_NAME==design_1_controlador_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_decodificador_0_0/design_1_decodificador_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_decodificador_0_0 || ORIG_REF_NAME==design_1_decodificador_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_div_0_0/design_1_div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_div_0_0 || ORIG_REF_NAME==design_1_div_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_div_4_0_0/design_1_div_4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_div_4_0_0 || ORIG_REF_NAME==design_1_div_4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_0/design_1_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_0 || ORIG_REF_NAME==design_1_debouncer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_1_0/design_1_debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_1_0 || ORIG_REF_NAME==design_1_debouncer_1_0} -quiet] -quiet

# XDC: c:/Users/UTEC-5695/Desktop/Archivos Raul/casi_ultimo/casi_ultimo.gen/sources_1/bd/design_1/design_1_ooc.xdc
