set_property IOSTANDARD LVCMOS33 [get_ports clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports signalPWM_0]

set_property IOSTANDARD LVCMOS33 [get_ports sw0_0]
set_property IOSTANDARD LVCMOS33 [get_ports sw1_0]
set_property IOSTANDARD LVCMOS33 [get_ports sw2_0]


set_property IOSTANDARD LVCMOS33 [get_ports boton_0]
set_property IOSTANDARD LVCMOS33 [get_ports boton_1]

set_property IOSTANDARD LVCMOS33 [get_ports senal_boton_0]
set_property IOSTANDARD LVCMOS33 [get_ports senal_boton_1]
set_property IOSTANDARD LVCMOS33 [get_ports senal_salida_2_1]
set_property IOSTANDARD LVCMOS33 [get_ports senal_salida_2_0]
set_property PACKAGE_PIN A4 [get_ports senal_boton_0]
set_property PACKAGE_PIN A3 [get_ports senal_boton_1]
set_property PACKAGE_PIN B3 [get_ports senal_salida_2_0]
set_property PACKAGE_PIN A2 [get_ports senal_salida_2_1]
set_property PACKAGE_PIN C3 [get_ports boton_0]
set_property PACKAGE_PIN M4 [get_ports boton_1]
set_property PACKAGE_PIN N11 [get_ports signalPWM_0]
set_property PACKAGE_PIN M2 [get_ports sw0_0]
set_property PACKAGE_PIN L2 [get_ports sw1_0]
set_property PACKAGE_PIN L3 [get_ports sw2_0]
set_property PACKAGE_PIN H4 [get_ports clk_0]
set_property DRIVE 12 [get_ports senal_boton_0]
